---
- name: Atualizar Windows com Ansible
  gather_facts: no
  hosts: all
  tasks:
    - name: Verifica atualizações disponíveis
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: updates_disponiveis

    - name: Instala atualizações encontradas
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      when: updates_disponiveis.found_update_count > 0

